Update camera cordova plugin
meteor/mobile-packages pull request #150
Opened 2021-08-25 13:09 UTC by StorytellerCZ

Updated the camera codova plugin to 4.0.3
Changelog: https://github.com/apache/cordova-plugin-camera/blob/master/RELEASENOTES.md#403-apr-12-2018

More could be done, but I think this is a good first step.

2021-08-26 02:36 UTC, filipenevola requested changes

2021-08-31 15:47 UTC, StorytellerCZ commented on packages/mdg:camera/package.js
> +  api.versionsFrom("METEOR@1.3");
Reverted

2021-09-02 00:55 UTC, filipenevola commented
@StorytellerCZ were these changes tested in iOS and Android?

2021-10-05 18:32 UTC, StorytellerCZ commented
@filipenevola With 2.5, had to upgrade to v6. Tested on Android device and it works well. But we will have to release this after Meteor 2.5. Best to put it together with #156

2021-10-25 12:56 UTC, renanccastro approved these changes

2021-10-25 15:43 UTC, merged