Made images fit inside dialog. Introduced width specifier or magnific…
meteor/mobile-packages pull request #76
Opened 2015-08-28 15:38 UTC by mikkelking

Made it a bit smoother - preserves aspect ratio if in portrait mode, and images stay inside the box. Moved the buttons above the images for smaller screens

2019-10-07 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meteor/mobile-packages?pullRequest=76) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meteor/mobile-packages?pullRequest=76) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meteor/mobile-packages?pullRequest=76) it.</sub>

2021-08-25 12:33 UTC, StorytellerCZ requested changes
Looks like there is a confusion on the location of the files in the repository.

2021-08-25 12:33 UTC, StorytellerCZ commented on packages/camera/package.js
> +  name: "mikkelking:camera",
I think there is a bit of a confusion on getting the package location in the repo.

2021-08-31 15:42 UTC, StorytellerCZ commented on packages/camera/package.js
> +  name: "mikkelking:camera",
Yes, both the package name and package should be `mdg:camera`.

2021-09-29 12:02 UTC, StorytellerCZ commented
This PR is malformed. The folder for the camera package is wrong which means that it looks like you are just creating a new package. It should be in `mdg:camera` folder. Please fix, so that we can proceed.

2021-09-29 21:22 UTC, filipenevola commented
It's probably easier to open a new PR.

2021-09-29 21:22 UTC, closed without merging